// Comprehensive list of book genres
export const BOOK_GENRES = [
  "Fiction",
  "Non-Fiction",
  "Mystery & Thriller",
  "Romance",
  "Science Fiction",
  "Fantasy",
  "Horror",
  "Biography & Autobiography",
  "History",
  "Self-Help",
  "Business & Economics",
  "Health & Fitness",
  "Travel",
  "Cooking",
  "Art & Design",
  "Science & Technology",
  "Philosophy",
  "Religion & Spirituality",
  "Poetry",
  "Drama",
  "Children's Books",
  "Young Adult",
  "Comics & Graphic Novels",
  "True Crime",
  "Sports",
  "Politics",
  "Psychology",
  "Education",
  "Reference",
  "Other",
]

// Genre categories for better organization
export const GENRE_CATEGORIES = {
  "Popular Fiction": ["Fiction", "Mystery & Thriller", "Romance", "Science Fiction", "Fantasy", "Horror"],
  "Non-Fiction": [
    "Non-Fiction",
    "Biography & Autobiography",
    "History",
    "Self-Help",
    "Business & Economics",
    "Health & Fitness",
    "Travel",
    "True Crime",
  ],
  "Academic & Reference": [
    "Science & Technology",
    "Philosophy",
    "Religion & Spirituality",
    "Politics",
    "Psychology",
    "Education",
    "Reference",
  ],
  "Arts & Literature": ["Poetry", "Drama", "Art & Design", "Cooking"],
  "Age-Specific": ["Children's Books", "Young Adult"],
  "Special Formats": ["Comics & Graphic Novels"],
  "Sports & Recreation": ["Sports"],
  Other: ["Other"],
}

// Get genre color for UI display
export const getGenreColor = (genre) => {
  const colorMap = {
    Fiction: "blue",
    "Non-Fiction": "green",
    "Mystery & Thriller": "red",
    Romance: "pink",
    "Science Fiction": "purple",
    Fantasy: "magenta",
    Horror: "volcano",
    "Biography & Autobiography": "orange",
    History: "gold",
    "Self-Help": "lime",
    "Business & Economics": "cyan",
    "Health & Fitness": "geekblue",
    Travel: "blue",
    Cooking: "orange",
    "Art & Design": "purple",
    "Science & Technology": "cyan",
    Philosophy: "geekblue",
    "Religion & Spirituality": "gold",
    Poetry: "magenta",
    Drama: "red",
    "Children's Books": "lime",
    "Young Adult": "pink",
    "Comics & Graphic Novels": "volcano",
    "True Crime": "red",
    Sports: "green",
    Politics: "blue",
    Psychology: "purple",
    Education: "cyan",
    Reference: "default",
    Other: "default",
  }

  return colorMap[genre] || "default"
}
